export const userTypes = {
    CREATE_USER : 'CREATE_USER',
    EDIT_USER : 'EDIT_USER',
    LOGIN_USER : 'LOGIN_USER',
    UPDATE_LOCATION : 'UPDATE_LOCATION',
    LOGOUT: 'LOGOUT',
    ADD_SEARCH : 'ADD_SEARCH',
    CREATE_ORDER : 'CREATE_ORDER',
    ADD_CARD: 'ADD_CARD',
    ADD_ORDER : 'ADD_ORDER',
    RESET_ORDER : 'RESET_ORDER'

}

export const loadingTypes =  {
  TOGGLE_LOADING: 'TOGGLE_LOADING'
}

